import "./globals.css";
import NavBar from "./components/navBar";
import Footer from "./components/footer";
import { UserProvider } from "./context/userContext";

export const metadata = {
  title: "NEXTGEN CAMPUS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <NavBar />
          <div className="all">{children}</div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
